### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'is_prerelease'

### ISSUE THREAD

**Issue by SendDerek** [svx/pyramid-buildout#5]
While following instructions in main README (https://github.com/svx/pyramid-buildout#readme), I get to the step where we run `bin/buildout`, and I'm met with the following error.  Would you happen to know anything about it?

```
Setting socket time out to 3 seconds.
While:
  Installing.
  Loading extensions.
  Getting distribution for 'buildout.threatlevel'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 467, in install
    self._load_extensions()
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 995, in _load_extensions
    newest=self.newest, allow_hosts=self._allow_hosts)
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 234, in _satisfied
    return None, self._obtain(req, source)
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 420, in _obtain
    if _final_version(dist.parsed_version)
  File "/Users/derek/pyramid/buildout-test/buildout/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 1408, in _final_version
    return not parsed_version.is_prerelease
AttributeError: 'tuple' object has no attribute 'is_prerelease'
```

I'm running Python 2.7.6.  Not sure what else might be of use, but the Google's don't show any answers as of yet.  Any help would be appreciated.

**Comment by SendDerek** [comment]
Actually, I may have found something that will get me going in the right direction:
https://github.com/buildout/buildout/pull/219
